import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/lib/contexts/appContext";
import UrlToast from "@/components/UrlToast";
import UrlAuthSync from "@/components/UrlAuthSync";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trello Clone - PG On Rails",
  description: "Generated by create next app, built with PG On Rails",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppContextProvider>
          {children}
          <Suspense>
            <UrlToast />
            <UrlAuthSync />
            <Toaster />
          </Suspense>
        </AppContextProvider>
      </body>
    </html>
  );
}
